# @package _global_

# Defaults for training for the PushT dataset.

seed: 100000
dataset_repo_id: absolutebogus

hdf5_data_dir: /home/hemanth/imitation_learning/hdf5/dec_4/sim

# hdf5_data_dir: /home/hemanth/imitation_learning/hdf5/small_dataset_oct_10_14/sim
hydra:
  job:
    name: red_plastic_multiple_dec5
override_dataset_stats:
  observation.images.cam1:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  observation.images.cam2:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  observation.images.cam3:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  # TODO(rcadene, alexander-soare): we override state and action stats to use the same as the pretrained model
  # from the original codebase, but we should remove these and train our own pretrained model
  observation.state:
    min: [-360, 0]
    max: [360, 120]
  action:
    min: [126.6000, -752.2200, 124.2200, -180, 0.0000]
    max: [599.7500, 468.9600, 1299.1801, 180, 1.0000]

training:
  offline_steps: 250000
  online_steps: 0
  eval_freq: -1
  save_freq: 25000
  save_checkpoint: true
  num_workers: 16

  batch_size: 8
  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1

  # VQ-BeT specific
  vqvae_lr: 1.0e-3
  n_vqvae_training_steps: 20000
  bet_weight_decay: 2e-4
  bet_learning_rate: 5.5e-5
  bet_betas: [0.9, 0.999]

  delta_timestamps:
    observation.images.cam1: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.images.cam2: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.images.cam3: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, ${policy.n_action_pred_token} + ${policy.action_chunk_size} - 1)]"

eval:
  n_episodes: 50
  batch_size: 50

policy:
  name: vqbet

  # Input / output structure.
  n_obs_steps: 1
  # n_obs_steps: 5
  n_action_pred_token: 7
  action_chunk_size: 5

  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.images.cam1: [3, 480, 640]
    observation.images.cam2: [3, 480, 640]
    observation.images.cam3: [3, 480, 640]
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.images.cam1: mean_std
    observation.images.cam2: mean_std
    observation.images.cam3: mean_std

    observation.state: min_max
  output_normalization_modes:
    action: min_max

  # Architecture / modeling.
  # Vision backbone.
  vision_backbone: resnet18
  crop_shape: null
  # crop_shape: [84, 84]
  crop_is_random: False
  # pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1 # can only use this if you use batch norm instead of group norm
  pretrained_backbone_weights: null
  use_group_norm: True
  spatial_softmax_num_keypoints: 32
  # VQ-VAE
  n_vqvae_training_steps: ${training.n_vqvae_training_steps}
  vqvae_n_embed: 16
  vqvae_embedding_dim: 256
  vqvae_enc_hidden_dim: 128
  # VQ-BeT
  gpt_block_size: 500
  gpt_input_dim: 512
  gpt_output_dim: 512
  gpt_n_layer: 8
  gpt_n_head: 8
  gpt_hidden_dim: 512
  dropout: 0.1
  mlp_hidden_dim: 1024
  offset_loss_weight: 10000.
  primary_code_loss_weight: 5.0
  secondary_code_loss_weight: 0.5
  bet_softmax_temperature: 0.1
  sequentially_select: False
